# Generated by Django 3.2.4 on 2023-08-13 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('cctwitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(help_text='To display a variable use curly braces, eg {arg1}', max_length=4000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='managedtweet',
            options={'ordering': ['owner'], 'verbose_name': 'Managed Tweet', 'verbose_name_plural': 'Managed Tweets'},
        ),
        migrations.AddField(
            model_name='managedtweet',
            name='body_template_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data to be used in the template', null=True),
        ),
        migrations.AddField(
            model_name='managedtweet',
            name='delay',
            field=models.IntegerField(blank=True, default=None, help_text='If there is no schedule, delay sending this tweet by this many seconds', null=True),
        ),
        migrations.AddField(
            model_name='managedtweet',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Date and time to stop sending this tweet', null=True),
        ),
        migrations.AddField(
            model_name='managedtweet',
            name='expiry_times_sent',
            field=models.IntegerField(blank=True, default=None, help_text='Number of times to send this tweet', null=True),
        ),
        migrations.AddField(
            model_name='managedtweet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managedtweet',
            name='times_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='managedtweet',
            name='body',
            field=models.CharField(help_text='Body will be overriden by template if one is selected', max_length=4000),
        ),
        migrations.AlterField(
            model_name='managedtweet',
            name='crontab_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.crontabschedule'),
        ),
        migrations.AlterField(
            model_name='managedtweet',
            name='interval_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.intervalschedule'),
        ),
        migrations.AddField(
            model_name='managedtweet',
            name='body_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cctwitter.tweettemplate'),
        ),
    ]
