# Generated by Django 3.2.4 on 2023-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctwitter', '0005_alter_managedtweet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedtweet',
            name='body_template_data',
            field=models.JSONField(blank=True, default=list, help_text='Data to be used in the template', null=True),
        ),
    ]
