# Generated by Django 3.2.4 on 2023-08-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctwitter', '0006_alter_managedtweet_body_template_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedtweet',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
