# Generated by Django 3.2.4 on 2023-08-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctwitter', '0008_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='consumer_key',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='consumer_secret',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
