# Generated by Django 3.2.5 on 2023-08-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctwitter', '0010_auto_20230814_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='consumer_key',
            new_name='access_key',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='consumer_secret',
            new_name='access_key_secret',
        ),
    ]
