# Generated by Django 3.2.5 on 2023-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctwitter', '0011_auto_20230814_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='authorization_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='oauth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='oauth_token_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
