# Generated by Django 3.2.5 on 2023-08-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctwitter', '0012_auto_20230814_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedtweet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cctwitter.client'),
        ),
    ]
